---
driver:
  name: default
  options:
    managed: true
    login_cmd_template: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -l {user} {address}"

platforms:
  - name: chrony-resolute
  - name: chrony-noble
  - name: chrony-jammy
  - name: chrony-alma8
  - name: chrony-alma9
  - name: chrony-alma10

ansible:
  executor:
    backend: ansible-playbook
    args:
      ansible_playbook:
        - --inventory=${MOLECULE_SCENARIO_DIRECTORY}/inventory.yml
  env:
    ANSIBLE_FORCE_COLOR: true
  cfg:
    defaults:
      host_key_checking: false
  playbooks:
    create: create.yml
    destroy: destroy.yml
    converge: converge.yml
    prepare: prepare.yml

scenario:
  test_sequence:
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
